name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.0, 8.1 ]
        laravel: [ 8.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 5.6.*
            php: 7.1
            testbench: 3.6.*
          - laravel: 5.7.*
            php: 7.2
            testbench: 3.7.*
          - laravel: 5.8.*
            php: 7.2
            testbench: 3.8.*
          - laravel: 6.*
            php: 7.2
            testbench: 4.*
          - laravel: 6.*
            php: 8.0
            testbench: 4.*
          - laravel: 7.*
            php: 7.2
            testbench: 5.*
          - laravel: 7.*
            php: 8.0
            testbench: 5.*
          - laravel: 8.*
            php: 7.3
            testbench: 6.*
          - laravel: 8.*
            testbench: 6.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: composer update --with="illuminate/support:${{ matrix.laravel }}" --with="orchestra/testbench:${{ matrix.testbench }}" --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - if: github.event_name == 'push'
        name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
